local storage door-config
FrankOelsch/capstone-project pull request #10
Opened 2022-11-04 11:06 UTC by FrankOelsch

local storage door-config

2022-11-04 11:47 UTC, ThomasF85 requested changes
Please have a look at my comments.

2022-11-04 11:47 UTC, ThomasF85 commented on src/pages/Config.js
>    const messageRadiusRef = useRef(null);
You are working with these refs to do direct dom manipulation (setting textContent). This is not how you are supposed to work in React. Please use states to describe the state of your components and use the state to change the appearance and text of your components.

2022-11-04 11:47 UTC, ThomasF85 commented on src/pages/Config.js
> +  }, [config]);
You are saving the new config into the localStorage even if the values do not pass your "validation" from the other useeffect. Do you want to save invalid values in localStorage?

2022-11-04 11:47 UTC, ThomasF85 commented on src/pages/Config.js
> +
You might want to consider using a localStorage hook instead. It's easier to use and it also handles cases like null, undefined values in localStorage.

2022-11-04 13:14 UTC, FrankOelsch commented on src/pages/Config.js
> +
Have changed the suggested changes except the custom hook. Please give me your ok.

2022-11-04 13:25 UTC, Kheirah approved these changes
Well done!

2022-11-04 13:25 UTC, Kheirah commented on src/pages/Config.js
> +  // );
Try getting the hook to work before your next review =)

2022-11-04 13:36 UTC, FrankOelsch commented on src/pages/Config.js
> +  // );
Now also useLocalStorage with help from our studies.

2022-11-05 17:27 UTC, FrankOelsch commented
Now it works!

2022-11-05 17:28 UTC, merged