Us2
FrankOelsch/capstone-project pull request #3
Opened 2022-10-28 17:43 UTC by FrankOelsch

Userstory 2 realisiert.

2022-10-28 18:19 UTC, jecaps approved these changes

2022-10-29 11:19 UTC, Kheirah requested changes
Very good first pull request!

I made some changes to your code to make it leaner. Don't be scared that the changes are so numerous. Your code does work 100%. But it's rather bloated with unnecessary states and event listeners which you don't need.

Please take an attentive look at the suggested changes, make sure to understand them and adjust your code accordingly. 👨‍💻

2022-10-29 11:19 UTC, Kheirah commented on src/pages/Config.js
> +  }, [show]);
```suggestion
useEffect(() => {
    if (isNaN(gateHeight) || isNaN(gateWidth)) setQm("--");
    else
      setQm(
        ((+gateWidth * +gateHeight) / 1000000).toLocaleString(undefined, {
          maximumFractionDigits: 2,
          minimumFractionDigits: 2,
        })
      );
  }, [gateHeight, gateWidth]);
```
Add a check for valid height and width values and display some kind of invalid input state "--".
Additionally, the useEffect hook responds to changes of said height and width values instead of an intermediate show state which merely functioned as a proxy for gateWidth and gateHeight.

2022-10-29 11:19 UTC, Kheirah commented on src/pages/Config.js
> +      ))}
```suggestion
      <StyledInput
        type="text"
        onChange={(event) => setGateWidth(event.target.value)}
        value={gateWidth}
      ></StyledInput>
      {isNaN(gateWidth) ? (
        <StyledMessage>Bitte nur Zahlen eingeben!</StyledMessage>
      ) : +gateWidth < 1000 || +gateWidth > 5000 ? (
        <StyledMessage>
          Zulässige Werte für Höhe: 1000 bis 5000 mm
        </StyledMessage>
      ) : null}
      <label htmlFor="gateH">Toröffnung-Höhe in mm</label>
      <StyledInput
        type="text"
        onChange={(event) => setGateHeight(event.target.value)}
        value={gateHeight}
      ></StyledInput>
      {isNaN(gateHeight) ? (
        <StyledMessage>Bitte nur Zahlen eingeben!</StyledMessage>
      ) : +gateHeight < 1800 || +gateHeight > 3000 ? (
        <StyledMessage>
          Zulässige Werte für Höhe: 1800 bis 3000 mm
        </StyledMessage>
      ) : null}
```
You no longer need separate event listeners. Instead, you can use the onChange event listener only.
In case of errors, you display the StyledMessage with the appropriate error message.

2022-10-29 11:19 UTC, Kheirah commented on src/pages/Config.js
> +  }
```suggestion

```
You can entirely get rid of that block of code since we've rendered it obsolete with our other changes.

2022-10-29 11:19 UTC, Kheirah commented on src/pages/Config.js
> +`;
```suggestion
  margin-bottom: 10px;
`;
```
Add some additional margin to get some space below the message.

2022-10-29 13:13 UTC, FrankOelsch commented
I have understood your recommended code changes and have incorporated them accordingly. Thanks a lot!

2022-10-29 14:04 UTC, Kheirah approved these changes
Looking good!

2022-10-29 15:36 UTC, merged