Simple cart
FrankOelsch/capstone-project pull request #7
Opened 2022-11-02 11:39 UTC by FrankOelsch

New page Cart, 
New styled components Item and TextInput, 
fuzzy search, 
routing to cart

2022-11-02 13:40 UTC, mpagels requested changes
Found some semantically issues and left some questions. Pls review.

2022-11-02 13:47 UTC, FrankOelsch commented on src/components/Item.js
> +    <StyledH3 variante={inCart} id={id} onClick={(e) => onSelect(e)}>
Right, I do not need, have deleted it.

2022-11-02 14:04 UTC, FrankOelsch commented on src/components/input/TextInput.js
> +      return false;
Yes, event. Saw that 'which' should not be used, used 'key' instead.

2022-11-02 14:11 UTC, FrankOelsch commented on src/pages/Cart.js
> +    });
It should only work in principle, nothing is stored yet, comes only with the next userstory (localStorage).

2022-11-02 14:17 UTC, FrankOelsch commented on src/pages/Cart.js
> +      <StyledH2>Artikel-Suche:</StyledH2>
Right, changed it to 'article'.

2022-11-02 14:19 UTC, FrankOelsch commented on src/pages/Cart.js
> +      <StyledH2>Artikel-Suche:</StyledH2>
Thank you for the review!

2022-11-02 14:27 UTC, FrankOelsch commented on src/pages/Cart.js
> +    });
Strange, now the toggle suddenly does not work anymore...

2022-11-02 17:14 UTC, FrankOelsch commented on src/pages/Cart.js
> +    });
Found my thinking error. Now it works.

2022-11-03 08:26 UTC, merged

2022-11-03 09:42 UTC, Kheirah commented on src/pages/Cart.js
> +    });
```suggestion
    if (!toggleID) return;

    setData(
      data.map((item) => {
        if (item.id === toggleID) {
          setToggleID("");
          return { ...item, inCart: !item.inCart };
        } else {
          return item;
        }
      })
    );
    }

```
Martin is right in pointing out that React does not "think" that way. Whenever you want to change state, you need to use the respective setState method.